import type { Metadata } from "next";
import { ArrowRight } from "lucide-react";
import { ListingHero } from "@/components/content/listing-hero";
import { ServiceGrid } from "@/components/home/service-grid";
import { ButtonLink } from "@/components/ui/button";
import { pageMetadata } from "@/lib/metadata";

export const metadata:Metadata=pageMetadata("企业服务","AI建站、独立站增长、AI广告投放、出海营销、SEO与GEO、海外社媒、全球发布和企业AI解决方案。","/services");
export default function ServicesPage(){return <><ListingHero eyebrow="Enterprise Growth Services" title="从AI能力到全球增长结果" description="AI Global以产品化服务连接市场洞察、网站、内容、广告、搜索、社媒和企业工作流。所有业务由AI Global统一组织与交付。" stats={[{value:"8",label:"核心服务产品"},{value:"诊断先行",label:"合作原则"},{value:"全球市场",label:"业务范围"}]}/><section className="section-pad bg-[var(--paper)]"><div className="container-main"><ServiceGrid/></div></section><section className="bg-white py-20"><div className="container-main grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[var(--brand-dark)]">How we work</p><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-.04em] md:text-5xl">一套对结果负责的协作方式</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">先理解市场和业务约束，再选择渠道与工具。需要跨领域交付时，由AI Global专业交付团队与认证生态合作伙伴协同完成。</p></div><div className="grid gap-3 md:grid-cols-2">{["从业务目标与现状诊断开始","给出清晰范围、里程碑和责任边界","用小规模验证降低项目风险","保留数据、内容与关键资产控制权","定期复盘真实指标，不制造虚假承诺","交付文档、培训与可持续运营机制"].map((item,index)=><div key={item} className="flex items-start gap-3 rounded-2xl border border-[var(--line)] p-5"><span className="font-mono text-[10px] text-[var(--brand-dark)]">0{index+1}</span><p className="text-sm font-semibold leading-6">{item}</p></div>)}</div></div></section><section className="bg-[var(--orange)] py-20"><div className="container-main flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em]">Start with a diagnosis</p><h2 className="mt-5 max-w-4xl font-display text-4xl font-semibold tracking-[-.04em] md:text-6xl">还不确定该选择哪项服务？</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#4a260e]">提交现状、目标市场与核心问题，我们会先判断问题、优先级和适合的合作方式。</p></div><ButtonLink href="/contact" variant="dark" size="lg">预约需求诊断<ArrowRight className="size-4"/></ButtonLink></div></section></>}
