import type { Metadata } from "next";
import { ArrowRight } from "lucide-react";
import { ListingHero } from "@/components/content/listing-hero";
import { ServiceGrid } from "@/components/home/service-grid";
import { ButtonLink } from "@/components/ui/button";
import { pageMetadata } from "@/lib/metadata";

export const metadata:Metadata=pageMetadata("AI电商出海服务","跨境电商增长诊断、AI独立站、商品内容与视觉、广告投放、SEO/GEO、智能客服与自动化服务。","/services");
export default function ServicesPage(){return <><ListingHero eyebrow="AI Commerce Growth Services" title="从AI能力到跨境电商增长结果" description="AI Global围绕市场、商品、独立站、内容、广告、搜索与客户运营提供六条产品化服务，全部由AI Global统一组织与交付。" stats={[{value:"6",label:"核心服务产品"},{value:"诊断先行",label:"合作原则"},{value:"跨境电商",label:"唯一业务主轴"}]}/><section className="section-pad bg-[var(--paper)]"><div className="container-main"><ServiceGrid/></div></section><section className="bg-white py-20"><div className="container-main grid gap-10 lg:grid-cols-[.75fr_1.25fr] lg:items-start"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[var(--brand-dark)]">How we work</p><h2 className="mt-5 font-display text-4xl font-semibold tracking-[-.04em] md:text-5xl">一套对经营结果负责的协作方式</h2><p className="mt-5 text-sm leading-7 text-[var(--muted)]">先理解商品、市场、渠道和经营约束，再选择AI能力与执行路径。需要跨领域交付时，由AI Global专业交付团队与认证生态合作伙伴协同完成。</p></div><div className="grid gap-3 md:grid-cols-2">{["从商品、市场与经营数据诊断开始","给出清晰范围、里程碑和责任边界","用小批SKU或小额流量验证关键假设","保留数据、内容与店铺资产控制权","复盘转化、成本、质量与效率指标","交付文档、培训与可持续运营机制"].map((item,index)=><div key={item} className="flex items-start gap-3 rounded-2xl border border-[var(--line)] p-5"><span className="font-mono text-[10px] text-[var(--brand-dark)]">0{index+1}</span><p className="text-sm font-semibold leading-6">{item}</p></div>)}</div></div></section><section className="bg-[var(--orange)] py-20"><div className="container-main flex flex-col gap-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em]">Start with a diagnosis</p><h2 className="mt-5 max-w-4xl font-display text-4xl font-semibold tracking-[-.04em] md:text-6xl">还不确定跨境增长卡在哪里？</h2><p className="mt-4 max-w-2xl text-sm leading-7 text-[#4a260e]">提交商品、渠道、目标市场和核心问题，我们会先判断优先级，再建议诊断、项目或长期合作方式。</p></div><ButtonLink href="/contact" variant="dark" size="lg">预约增长诊断<ArrowRight className="size-4"/></ButtonLink></div></section></>}
