import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowDown, CheckCircle2 } from "lucide-react";
import { ListingHero } from "@/components/content/listing-hero";
import { knowledge, knowledgeCategories } from "@/data/knowledge";
import { pageMetadata } from "@/lib/metadata";

export function generateStaticParams(){return knowledgeCategories.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=knowledgeCategories.find(x=>x.slug===slug);return c?pageMetadata(c.path,`从入门到实战系统学习${c.name}。`,`/knowledge/path/${slug}`):{};}
export default async function LearningPath({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const category=knowledgeCategories.find(x=>x.slug===slug);if(!category)notFound();const items=knowledge.filter(i=>i.categorySlug===slug).sort((a,b)=>["入门","进阶","实战"].indexOf(a.level)-["入门","进阶","实战"].indexOf(b.level));return <><ListingHero eyebrow="Learning Path" title={category.path} description={`按“理解基础 → 建立方法 → 完成实战”的节奏学习${category.name}。`}/><section className="bg-[var(--paper)] py-16"><div className="container-reading">{items.map((item,index)=><div key={item.slug} className="relative grid grid-cols-[48px_1fr] gap-5 pb-5"><div className="flex flex-col items-center"><span className="flex size-10 items-center justify-center rounded-full bg-[var(--ink)] font-mono text-xs text-white">{index+1}</span>{index<items.length-1&&<span className="my-2 h-full w-px bg-[var(--line-strong)]"/>}</div><a href={`/knowledge/${item.slug}`} className="mb-3 rounded-[22px] border border-[var(--line)] bg-white p-6 hover:border-[var(--brand)]"><div className="flex items-center justify-between"><span className="text-xs font-bold text-[var(--brand-dark)]">{item.level} · {item.topic}</span><CheckCircle2 className="size-4 text-[#a1ada8]"/></div><h2 className="mt-3 text-xl font-semibold">{item.title}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{item.description}</p>{index<items.length-1&&<ArrowDown className="mt-4 size-4 text-[var(--brand-dark)]"/>}</a></div>)}</div></section></>}
