import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, BookOpenCheck, Route, SearchCheck } from "lucide-react";
import { ListingHero } from "@/components/content/listing-hero";
import { KnowledgeCard } from "@/components/content/knowledge-card";
import { ButtonLink } from "@/components/ui/button";
import { knowledge, knowledgeCategories } from "@/data/knowledge";
import { pageMetadata } from "@/lib/metadata";

export const metadata:Metadata=pageMetadata("AI电商出海知识库","覆盖AI电商战略、选品与商品内容、独立站、广告、SEO/GEO、智能客服与自动化的系统知识库。","/knowledge");
export default function KnowledgePage(){return <><ListingHero eyebrow="AI Commerce Knowledge" title="AI电商出海知识库" description="不做泛AI技巧仓库。按跨境经营问题与学习路径组织方法、教程、模板、案例和FAQ。" stats={[{value:"6",label:"经营领域"},{value:"24",label:"首期结构内容"},{value:"3级",label:"权限体系"}]}/><section className="bg-white py-14"><div className="container-main"><div className="grid gap-4 md:grid-cols-3">{[{icon:Route,title:"按学习路径",text:"从AI电商认知到可执行的经营任务。",href:"/knowledge/path/ai-commerce"},{icon:SearchCheck,title:"按经营问题",text:"围绕商品、广告、独立站、搜索和自动化查找答案。",href:"/search?type=knowledge"},{icon:BookOpenCheck,title:"会员深度内容",text:"跨境模板、完整案例与课程资料集中访问。",href:"/community/membership"}].map((item)=>{const Icon=item.icon;return <Link key={item.title} href={item.href} className="group rounded-[22px] border border-[var(--line)] p-6 hover:border-[var(--brand)]"><Icon className="size-5 text-[var(--brand-dark)]"/><h2 className="mt-5 text-lg font-bold">{item.title}</h2><p className="mt-2 text-sm text-[var(--muted)]">{item.text}</p><ArrowRight className="mt-5 size-4 transition group-hover:translate-x-1"/></Link>})}</div></div></section><section className="section-pad soft-grid bg-[var(--paper)]"><div className="container-main"><div className="flex items-end justify-between"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[var(--brand-dark)]">Atlas</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-.035em]">六大跨境经营领域</h2></div></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{knowledgeCategories.map((category,index)=><Link key={category.slug} href={`/knowledge/category/${category.slug}`} className="group rounded-[24px] border border-[var(--line)] bg-white p-6"><span className="font-mono text-[10px] text-[#9aa6a1]">0{index+1}</span><h3 className="mt-7 text-xl font-bold">{category.name}</h3><div className="mt-4 flex flex-wrap gap-1.5">{category.topics.map(topic=><span key={topic} className="rounded-full bg-[var(--paper)] px-2 py-1 text-[10px] text-[var(--muted)]">{topic}</span>)}</div><p className="mt-6 text-xs font-semibold text-[var(--brand-dark)]">{category.path} →</p></Link>)}</div></div></section><section className="section-pad bg-white"><div className="container-main"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="font-mono text-[10px] font-bold uppercase tracking-[.18em] text-[var(--brand-dark)]">Recently Updated</p><h2 className="mt-4 font-display text-4xl font-semibold tracking-[-.035em]">最近更新</h2></div><ButtonLink href="/search?type=knowledge" variant="outline">搜索全部知识</ButtonLink></div><div className="mt-9 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{knowledge.slice(0,12).map(item=><KnowledgeCard key={item.slug} item={item}/>)}</div></div></section></>}
