import Link from "next/link";
import { ArrowRight, ArrowUpRight, CalendarDays, Check, CircleDot, Download, Lightbulb, MapPin, MessageCircle, MoveRight, Sparkles, Users } from "lucide-react";
import { NetworkVisual } from "@/components/home/network-visual";
import { ServiceGrid } from "@/components/home/service-grid";
import { ButtonLink } from "@/components/ui/button";
import { SectionHeading } from "@/components/ui/section-heading";
import { NewsletterForm } from "@/components/forms/newsletter-form";
import { news } from "@/data/news";
import { knowledgeCategories } from "@/data/knowledge";
import { tools } from "@/data/tools";
import { cases } from "@/data/cases";
import { communityTopics, events, reports } from "@/data/resources";
import { formatDate } from "@/lib/utils";

export default function HomePage() {
  const leadNews = news[0];
  return <>
    <section className="noise relative overflow-hidden bg-[var(--ocean)] text-white">
      <div className="absolute left-[-10%] top-[-30%] h-[650px] w-[650px] rounded-full bg-[var(--brand)]/[.07] blur-[100px]" />
      <div className="container-main grid min-h-[calc(100vh-104px)] items-center gap-10 py-16 lg:grid-cols-[1.05fr_.95fr] lg:py-20">
        <div className="relative z-10 min-w-0">
          <div className="reveal inline-flex items-center gap-3 rounded-full border border-white/12 bg-white/[.04] px-4 py-2 font-mono text-[10px] font-bold uppercase tracking-[.2em] text-[var(--brand)]"><span className="size-1.5 rounded-full bg-[var(--violet)]" />AI × Commerce × Global Growth</div>
          <h1 className="mt-8 max-w-3xl break-words font-display text-[clamp(2.75rem,11vw,6.9rem)] font-semibold leading-[.95] tracking-[-.065em]">用AI重构<br/><span className="text-brand-gradient">电商与全球化</span><br className="sm:hidden"/>增长</h1>
          <p className="mt-7 max-w-2xl text-base leading-8 text-white/62 md:text-lg">从行业资讯、工具和知识，到AI建站、广告投放、SEO与出海营销，为中国企业提供面向全球市场的一站式AI增长支持。</p>
          <div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/contact" size="lg">获取AI出海方案<ArrowRight className="size-4" /></ButtonLink><ButtonLink href="/knowledge" size="lg" variant="outline" className="border-white/18 text-white hover:bg-white/8">探索知识库</ButtonLink><ButtonLink href="/community" size="lg" variant="ghost" className="text-white/70 hover:bg-white/8">加入AI出海社群</ButtonLink></div>
          <div className="mt-12 flex flex-wrap gap-x-5 gap-y-3 border-t border-white/10 pt-5">{["AI智能建站","AI广告投放","SEO与GEO","海外社媒","AI产品出海","企业AI服务"].map((tag) => <span key={tag} className="flex items-center gap-2 text-xs text-white/44"><CircleDot className="size-3 text-[var(--brand)]" />{tag}</span>)}</div>
        </div>
        <div className="relative hidden lg:block"><NetworkVisual /></div>
      </div>
      <div className="absolute bottom-5 left-1/2 hidden -translate-x-1/2 items-center gap-3 font-mono text-[9px] tracking-[.18em] text-white/25 lg:flex"><span className="h-px w-16 bg-white/15" />SCROLL TO EXPLORE<span className="h-px w-16 bg-white/15" /></div>
    </section>

    <section className="section-pad bg-[var(--paper)]"><div className="container-main"><SectionHeading eyebrow="Enterprise Services / 01" title="从AI能力到全球增长结果" description="不是零散工具采购，而是围绕真实业务目标，把洞察、内容、渠道、技术与数据连接起来。" link="/services" linkLabel="全部企业服务" /><ServiceGrid /></div></section>

    <section className="section-pad overflow-hidden bg-white"><div className="container-main">
      <SectionHeading eyebrow="Daily Briefing / 02" title="今日AI出海快讯" description="只保留值得关注的变化、它对业务的含义，以及可追溯的原始来源。" link="/news" linkLabel="查看全部资讯" />
      <div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr]">
        <Link href={`/news/${leadNews.slug}`} className="group relative flex min-h-[440px] flex-col justify-end overflow-hidden rounded-[30px] bg-[var(--ocean)] p-7 text-white md:p-10">
          <div className="absolute inset-0 soft-grid opacity-30"/><div className="absolute -right-16 -top-16 size-72 rounded-full border border-[var(--brand)]/25"/><div className="absolute right-6 top-6 font-mono text-[10px] tracking-[.16em] text-white/35">FEATURED / {leadNews.publishedAt}</div>
          <div className="relative"><span className="rounded-full bg-[var(--brand)] px-3 py-1.5 text-xs font-bold text-[#062118]">{leadNews.category}</span><h3 className="mt-6 max-w-2xl text-balance font-display text-3xl font-semibold leading-tight tracking-[-.035em] md:text-5xl">{leadNews.title}</h3><p className="mt-5 max-w-2xl text-sm leading-7 text-white/55 md:text-base">{leadNews.summary}</p><span className="mt-7 inline-flex items-center gap-2 text-sm font-semibold text-[var(--brand)]">阅读编辑摘要<ArrowUpRight className="size-4 transition group-hover:translate-x-1 group-hover:-translate-y-1" /></span></div>
        </Link>
        <div className="divide-y divide-[var(--line)]">{news.slice(1, 7).map((item, index) => <Link key={item.slug} href={`/news/${item.slug}`} className="group grid grid-cols-[38px_1fr_auto] gap-3 py-5 first:pt-1"><span className="font-mono text-[10px] text-[#a4afab]">0{index + 2}</span><div><span className="text-[10px] font-bold text-[var(--brand-dark)]">{item.category}</span><h3 className="mt-1.5 text-[15px] font-semibold leading-6 group-hover:text-[var(--brand-dark)]">{item.title}</h3><p className="mt-1 text-xs text-[var(--muted)]">{item.source} · {formatDate(item.publishedAt)}</p></div><ArrowUpRight className="mt-1 size-4 text-[#a4afab] transition group-hover:text-[var(--brand-dark)]" /></Link>)}</div>
      </div>
      <div className="mt-10 flex flex-col items-start justify-between gap-5 rounded-2xl border border-[var(--line)] bg-[var(--paper)] p-5 sm:flex-row sm:items-center"><div><p className="font-semibold">每日快讯，不追热点噪音</p><p className="mt-1 text-sm text-[var(--muted)]">精选行业动态、平台变化与增长方法。</p></div><NewsletterForm compact /></div>
    </div></section>

    <section className="section-pad soft-grid bg-[var(--paper)]"><div className="container-main"><SectionHeading eyebrow="Editors’ Choice / 03" title="本周最值得关注" description="深度指南、实战方法、平台变化与商业机会，由编辑团队建立内容之间的联系。" />
      <div className="grid auto-rows-[minmax(190px,auto)] gap-4 lg:grid-cols-12">
        <Link href="/knowledge/geo-foundations" className="group relative overflow-hidden rounded-[28px] bg-[#0b2547] p-7 text-white lg:col-span-7 lg:row-span-2 md:p-9"><span className="font-mono text-[10px] uppercase tracking-[.18em] text-[var(--brand)]">Deep Guide</span><h3 className="mt-8 max-w-xl font-display text-3xl font-semibold leading-tight md:text-5xl">AI搜索时代，品牌如何成为“可引用的答案”</h3><p className="mt-5 max-w-lg text-sm leading-7 text-white/56">从实体信息、专业作者、内容结构到第三方信号，建立GEO的长期基础。</p><ArrowUpRight className="absolute bottom-8 right-8 size-8 text-[var(--brand)] transition group-hover:rotate-45" /></Link>
        {news.slice(4,8).map((item) => <Link key={item.slug} href={`/news/${item.slug}`} className="group rounded-[24px] border border-[var(--line)] bg-white p-6 lg:col-span-5"><span className="text-[10px] font-bold text-[var(--brand-dark)]">{item.category}</span><h3 className="mt-3 text-xl font-semibold leading-7 tracking-[-.02em] group-hover:text-[var(--brand-dark)]">{item.title}</h3><p className="mt-4 text-xs text-[var(--muted)]">{formatDate(item.publishedAt)}</p></Link>)}
        <Link href="/reports/geo-ai-search-guide" className="bg-brand-gradient relative overflow-hidden rounded-[24px] p-7 text-white lg:col-span-12"><div className="absolute -right-10 -top-20 size-56 rounded-full border border-white/15"/><span className="relative font-mono text-[10px] uppercase tracking-[.16em] text-white/75">Research / R04</span><div className="relative mt-5 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h3 className="font-display text-3xl font-semibold tracking-[-.03em]">GEO与AI搜索增长实践指南</h3><p className="mt-2 text-sm text-white/72">42页 · 品牌实体、可引用内容与监测方法</p></div><span className="flex items-center gap-2 text-sm font-bold">获取完整报告<Download className="size-4" /></span></div></Link>
      </div>
    </div></section>

    <section className="section-pad bg-white"><div className="container-main"><SectionHeading eyebrow="Knowledge Atlas / 04" title="从工具使用到全球增长的系统知识库" description="按业务领域、主题和学习路径组织知识。每一篇都说明它回答什么问题、适合谁，以及可以采取的下一步。" link="/knowledge" />
      <div className="grid border-l border-t border-[var(--line)] sm:grid-cols-2 lg:grid-cols-4">{knowledgeCategories.map((category, index) => <Link key={category.slug} href={`/knowledge/category/${category.slug}`} className="group min-h-64 border-b border-r border-[var(--line)] bg-white p-6 transition hover:bg-[var(--brand-wash)]"><span className="font-mono text-[10px] text-[#9ba8a3]">K / 0{index + 1}</span><h3 className="mt-7 text-xl font-bold tracking-[-.025em]">{category.name}</h3><div className="mt-5 flex flex-wrap gap-1.5">{category.topics.map((topic) => <span key={topic} className="rounded-full border border-[var(--line)] bg-white px-2.5 py-1 text-[10px] text-[var(--muted)]">{topic}</span>)}</div><div className="mt-7 flex items-center justify-between text-xs text-[var(--muted)]"><span>{category.count}篇内容 · {category.updated}</span><MoveRight className="size-4 transition group-hover:translate-x-1" /></div><p className="mt-3 text-xs font-semibold text-[var(--brand-dark)]">推荐：{category.path}</p></Link>)}</div>
    </div></section>

    <section className="section-pad bg-[var(--ocean)] text-white"><div className="container-main"><SectionHeading dark eyebrow="Tool Directory / 05" title="AI电商与出海工具库" description="围绕实际场景整理工具信息。我们不虚构评分、用户数量或未经核实的价格。" link="/tools" linkLabel="浏览全部工具" />
      <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{tools.slice(0, 12).map((tool) => <Link key={tool.slug} href={`/tools/${tool.slug}`} className="group flex min-h-44 flex-col rounded-2xl border border-white/10 bg-white/[.035] p-5 transition hover:border-[var(--brand)]/45 hover:bg-white/[.06]"><div className="flex items-start justify-between"><span className="flex size-10 items-center justify-center rounded-xl bg-white text-sm font-black text-[var(--ink)]">{tool.name.slice(0,2)}</span>{tool.editorPick && <span className="flex items-center gap-1 text-[9px] font-bold text-[var(--orange)]"><Sparkles className="size-3"/>编辑推荐</span>}</div><h3 className="mt-5 font-semibold">{tool.name}</h3><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/48">{tool.description}</p><div className="mt-auto flex items-end justify-between pt-4 text-[10px] text-white/35"><span>{tool.category} · {tool.pricing}</span><ArrowUpRight className="size-4 transition group-hover:text-[var(--brand)]" /></div></Link>)}</div>
      <div className="mt-8 flex flex-wrap gap-3"><ButtonLink href="/submit" variant="outline" className="border-white/15 text-white hover:bg-white/8">提交工具</ButtonLink><ButtonLink href="/partners" variant="ghost" className="text-white/65 hover:bg-white/8">申请品牌合作<ArrowUpRight className="size-4"/></ButtonLink></div>
    </div></section>

    <section className="section-pad bg-[var(--paper)]"><div className="container-main"><SectionHeading eyebrow="Practice / 06" title="AI驱动全球增长的真实实践" description="明确区分匿名案例、示范方案与自有案例。没有公开授权，就不展示客户Logo；没有可靠数据，就不编造增长数字。" link="/cases" />
      <div className="grid gap-4 lg:grid-cols-3">{cases.slice(0, 6).map((item, index) => <Link key={item.slug} href={`/cases/${item.slug}`} className={`group flex min-h-[330px] flex-col rounded-[26px] border p-6 ${index === 0 ? "border-transparent bg-[var(--global-blue)] text-white lg:col-span-2" : "border-[var(--line)] bg-white"}`}><div className="flex items-center justify-between"><span className={`rounded-full px-3 py-1 text-[10px] font-bold ${index === 0 ? "bg-white/15 text-white" : "bg-[var(--brand-wash)] text-[var(--brand-dark)]"}`}>{item.kind === "示范方案" ? "Sample Playbook / 示范方案" : item.kind}</span><span className="font-mono text-[10px] opacity-45">C0{index+1}</span></div><h3 className={`mt-7 font-display font-semibold leading-tight tracking-[-.03em] ${index === 0 ? "max-w-2xl text-4xl md:text-5xl" : "text-2xl"}`}>{item.title}</h3><p className="mt-4 text-sm leading-6 opacity-65">{item.challenge}</p><div className="mt-auto flex items-end justify-between pt-6"><span className="text-xs font-semibold">{item.industry} · {item.service}</span><ArrowUpRight className="size-5 transition group-hover:rotate-45" /></div></Link>)}</div>
    </div></section>

    <section className="section-pad bg-white"><div className="container-main"><SectionHeading eyebrow="Research / 07" title="AI电商与全球增长研究" description="以结构化方法、透明来源和可执行结论，沉淀行业变化与实践框架。" link="/reports" />
      <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{reports.map((report, index) => <Link key={report.slug} href={`/reports/${report.slug}`} className="group"><div className={`relative aspect-[3/4] overflow-hidden rounded-[20px] p-6 ${["bg-[#0b2547] text-white","bg-[#dfeaff] text-[#172b57]","bg-[#254edb] text-white","bg-[#7146c7] text-white"][index]}`}><div className="soft-grid absolute inset-0 opacity-25"/><span className="relative font-mono text-[9px] tracking-[.18em]">AI GLOBAL RESEARCH / {report.number}</span><h3 className="relative mt-16 font-display text-2xl font-semibold leading-tight tracking-[-.025em]">{report.title}</h3><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between border-t border-current/20 pt-4"><span className="text-[10px]">{report.pages ? `${report.pages} PAGES` : "COMING SOON"}</span><span className="font-display text-2xl">AG.</span></div></div><div className="mt-4 flex items-center justify-between"><span className="text-sm font-semibold">{report.status}</span><Download className="size-4 text-[var(--muted)] transition group-hover:text-[var(--brand-dark)]" /></div></Link>)}</div>
    </div></section>

    <section className="section-pad soft-grid bg-[var(--paper-2)]"><div className="container-main grid gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-center">
      <div><p className="font-mono text-[11px] font-bold uppercase tracking-[.2em] text-[var(--brand-dark)]">Community / 08</p><h2 className="mt-5 text-balance font-display text-4xl font-semibold leading-[1.08] tracking-[-.04em] md:text-6xl">加入AI出海<br/>实践者社区</h2><p className="mt-6 max-w-lg text-base leading-8 text-[var(--muted)]">AI Global Club连接跨境卖家、出海品牌、AI创业者、独立开发者和企业管理者，围绕真实问题交流与合作。</p><div className="mt-8 grid grid-cols-2 gap-3 text-sm">{["每周行业精选","AI工具与教程","会员知识库","行业分享","线下活动","案例交流","企业需求","合作机会"].map((item)=><span key={item} className="flex items-center gap-2"><Check className="size-4 text-[var(--brand-dark)]"/>{item}</span>)}</div><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="/community/apply">申请加入<Users className="size-4"/></ButtonLink><ButtonLink href="/community/membership" variant="outline">查看会员权益</ButtonLink></div></div>
      <div className="rounded-[30px] border border-[var(--line)] bg-white p-4 shadow-[0_30px_70px_rgba(18,33,43,.08)] md:p-7"><div className="flex items-center justify-between border-b border-[var(--line)] pb-5"><div><p className="text-sm font-bold">社区正在讨论</p><p className="mt-1 text-xs text-[var(--muted)]">真实问题 · 专业交流 · 基础审核</p></div><MessageCircle className="size-5 text-[var(--brand-dark)]"/></div><div className="divide-y divide-[var(--line)]">{communityTopics.slice(0,5).map((topic)=><Link href={`/community/topics#${topic.slug}`} key={topic.slug} className="group block py-5"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-bold text-[var(--brand-dark)]">{topic.category}</span><h3 className="mt-1.5 font-semibold leading-6 group-hover:text-[var(--brand-dark)]">{topic.title}</h3></div><span className="shrink-0 text-[10px] text-[var(--muted)]">{topic.replies}回复</span></div><p className="mt-2 text-xs text-[var(--muted)]">{topic.author} · {formatDate(topic.publishedAt)}</p></Link>)}</div></div>
    </div></section>

    <section className="section-pad bg-[var(--paper)]"><div className="container-main"><SectionHeading eyebrow="Events & Learning / 09" title="活动、课程与行业连接" description="线上直播、城市Meetup、训练营与企业交流，让知识进入真实的业务现场。" link="/events" />
      <div className="grid gap-4 lg:grid-cols-4">{events.map((event)=><Link key={event.slug} href={`/events/${event.slug}`} className="group flex min-h-[310px] flex-col rounded-[24px] border border-[var(--line)] bg-white p-6"><div className="flex justify-between"><span className="rounded-full bg-[var(--brand-wash)] px-3 py-1 text-[10px] font-bold text-[var(--brand-dark)]">{event.type}</span><span className="text-[10px] text-[var(--muted)]">{event.status}</span></div><h3 className="mt-7 text-xl font-semibold leading-7 tracking-[-.02em] group-hover:text-[var(--brand-dark)]">{event.title}</h3><div className="mt-auto space-y-2 pt-7 text-xs text-[var(--muted)]"><p className="flex items-center gap-2"><CalendarDays className="size-3.5"/>{formatDate(event.date)}</p><p className="flex items-center gap-2"><MapPin className="size-3.5"/>{event.location}</p></div></Link>)}</div>
    </div></section>

    <section className="bg-white py-20"><div className="container-main"><div className="rounded-[32px] border border-[var(--line)] bg-[var(--paper)] p-7 md:p-12"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr] lg:items-end"><div><Lightbulb className="size-6 text-[var(--orange)]"/><h2 className="mt-5 font-display text-3xl font-semibold tracking-[-.035em] md:text-5xl">每周获取一份<br/>AI出海精选</h2><p className="mt-4 text-sm leading-7 text-[var(--muted)]">行业动态、新工具、案例、增长方法、活动与商业机会。无噪音，可随时退订。</p></div><NewsletterForm /></div></div></div></section>

    <section className="bg-brand-gradient relative overflow-hidden py-20 text-white md:py-28"><div className="absolute -right-32 -top-40 size-[500px] rounded-full border border-white/15"/><div className="container-main relative"><p className="font-mono text-[10px] font-bold uppercase tracking-[.2em] text-white/75">Your next move</p><div className="mt-6 flex flex-col justify-between gap-9 lg:flex-row lg:items-end"><h2 className="max-w-4xl text-balance font-display text-4xl font-semibold leading-[1.05] tracking-[-.045em] md:text-7xl">用AI开启你的全球增长下一步</h2><div className="flex shrink-0 flex-wrap gap-3"><ButtonLink href="/contact" variant="dark" size="lg">获取AI出海方案<ArrowRight className="size-4"/></ButtonLink><ButtonLink href="/community" variant="outline" size="lg" className="border-white/25 text-white hover:bg-white/10">加入社群</ButtonLink></div></div></div></section>
  </>;
}
