import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { CalendarDays, MapPin, Ticket, Users } from "lucide-react";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ApplicationForm } from "@/components/forms/application-form";
import { JsonLd } from "@/components/seo/json-ld";
import { events, getEvent } from "@/data/resources";
import { pageMetadata } from "@/lib/metadata";
import { absoluteUrl, formatDate } from "@/lib/utils";

export function generateStaticParams(){return events.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const e=getEvent((await params).slug);return e?pageMetadata(e.title,e.description,`/events/${e.slug}`):{};}
export default async function EventDetail({params}:{params:Promise<{slug:string}>}){const e=getEvent((await params).slug);if(!e)notFound();const schema={"@context":"https://schema.org","@type":"Event",name:e.title,startDate:e.date,eventAttendanceMode:e.location.includes("线上")?"https://schema.org/OnlineEventAttendanceMode":"https://schema.org/OfflineEventAttendanceMode",location:{"@type":e.location.includes("线上")?"VirtualLocation":"Place",name:e.location,url:absoluteUrl(`/events/${e.slug}`)},description:e.description,organizer:{"@type":"Organization",name:"AI Global",url:absoluteUrl()}};return <><JsonLd data={schema}/><section className="bg-[var(--ocean)] py-16 text-white"><div className="container-reading"><Breadcrumbs light items={[{label:"活动",href:"/events"},{label:e.title}]}/><span className="mt-10 inline-block rounded-full bg-[var(--brand)] px-3 py-1 text-xs font-bold text-[#062118]">{e.status}</span><h1 className="mt-6 font-display text-4xl font-semibold leading-tight tracking-[-.04em] md:text-6xl">{e.title}</h1><p className="mt-6 text-lg leading-8 text-white/58">{e.description}</p></div></section><section className="section-pad bg-[var(--paper)]"><div className="container-main grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-1">{[{icon:CalendarDays,label:"时间",value:formatDate(e.date)},{icon:MapPin,label:"地点",value:e.location},{icon:Users,label:"嘉宾 / 名额",value:`${e.speaker} · ${e.capacity}`},{icon:Ticket,label:"费用",value:e.price}].map(i=>{const Icon=i.icon;return <div key={i.label} className="rounded-2xl border border-[var(--line)] bg-white p-5"><Icon className="size-5 text-[var(--brand-dark)]"/><p className="mt-4 text-xs text-[var(--muted)]">{i.label}</p><p className="mt-1 text-sm font-semibold">{i.value}</p></div>})}</div><div className="rounded-[26px] border border-[var(--line)] bg-white p-6 md:p-8"><h2 className="font-display text-3xl font-semibold">{e.status==="已结束"?"登记后续活动":"报名 / 候补申请"}</h2><p className="mt-3 mb-7 text-sm text-[var(--muted)]">提交信息后由运营团队审核并发送具体安排。首期不处理在线支付。</p><ApplicationForm kind="event" typeOptions={[e.title,"后续同类活动","企业内训咨询"]} submitLabel="提交报名"/></div></div></section></>}
