import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { ArrowRight, CheckCircle2 } from "lucide-react";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { ButtonLink } from "@/components/ui/button";
import { cases, getCase } from "@/data/cases";
import { pageMetadata } from "@/lib/metadata";

export function generateStaticParams(){return cases.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const item=getCase((await params).slug);return item?pageMetadata(item.title,item.challenge,`/cases/${item.slug}`):{};}
export default async function CaseDetail({params}:{params:Promise<{slug:string}>}){const item=getCase((await params).slug);if(!item)notFound();return <><section className="bg-[var(--ocean)] py-16 text-white"><div className="container-reading"><Breadcrumbs light items={[{label:"案例",href:"/cases"},{label:item.title}]}/><span className="mt-10 inline-block rounded-full bg-[var(--orange)] px-3 py-1.5 text-xs font-bold text-[#2c1407]">{item.kind==="示范方案"?"Sample Playbook / 示范方案":item.kind}</span><h1 className="mt-6 font-display text-4xl font-semibold leading-[1.08] tracking-[-.04em] md:text-6xl">{item.title}</h1><p className="mt-7 text-lg leading-8 text-white/58">{item.companyType} · {item.industry} · {item.duration}</p></div></section><section className="section-pad bg-[var(--paper)]"><div className="container-reading"><div className="grid gap-4 md:grid-cols-2">{[{label:"原始问题",value:item.challenge},{label:"解决方案",value:item.solution},{label:"使用的AI能力",value:item.capabilities.join("、")},{label:"核心结果",value:item.result}].map(block=><div key={block.label} className="rounded-[22px] border border-[var(--line)] bg-white p-6"><p className="text-xs font-bold text-[var(--brand-dark)]">{block.label}</p><p className="mt-3 text-sm leading-7 text-[var(--muted)]">{block.value}</p></div>)}</div><div className="prose-global mt-10"><h2>方法拆解</h2><p>项目从问题和业务约束开始，而不是从工具开始。团队先确认目标用户、现有流程、可用证据和成功标准，再将任务拆成可以验证的阶段。</p><ul><li>诊断：确认真正阻碍增长的关键环节。</li><li>设计：形成内容、体验、渠道与数据的协同方案。</li><li>验证：在可控范围内执行，记录质量和业务信号。</li><li>交接：沉淀模板、文档和后续复盘机制。</li></ul><h2>结果说明</h2><p>{item.result}</p>{item.kind==="示范方案"&&<blockquote>这是 Sample Playbook / 示范方案，用于展示解决问题的方法，不代表已完成客户项目，也不包含虚构客户或业绩数据。</blockquote>}</div><div className="mt-10 rounded-[24px] bg-[var(--orange)] p-7"><CheckCircle2 className="size-6"/><h2 className="mt-4 font-display text-3xl font-semibold">有相似问题？</h2><p className="mt-3 max-w-xl text-sm leading-7 text-[#5b3015]">提交你的目标市场、业务阶段和核心问题，获取适合的诊断与方案建议。</p><ButtonLink href={`/contact?service=${item.serviceSlug}`} variant="dark" className="mt-6">获取方案<ArrowRight className="size-4"/></ButtonLink></div></div></section></>}
