import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { ArrowRight, Check } from "lucide-react";
import { ButtonLink } from "@/components/ui/button";
import { enServiceDeliverables, enServices } from "@/data/en";
import { pageMetadata } from "@/lib/metadata";
export function generateStaticParams(){return enServices.map(({slug})=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const s=enServices.find(x=>x.slug===slug);return s?pageMetadata(s.title,s.description,`/en/services/${s.slug}`):{};}
export default async function EnglishService({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const en=enServices.find(x=>x.slug===slug);const deliverables=enServiceDeliverables[slug];if(!en||!deliverables)notFound();return <><section className="bg-[var(--ocean)] py-20 text-white"><div className="container-main"><Link href="/en" className="text-xs text-white/45">← AI Global English</Link><p className="mt-12 font-mono text-[10px] uppercase tracking-[.2em] text-[var(--brand)]">{en.name}</p><h1 className="mt-6 max-w-5xl font-display text-5xl font-semibold leading-[1.02] tracking-[-.05em] md:text-7xl">{en.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-white/58">{en.description}</p><ButtonLink href="/contact" className="mt-9" size="lg">Discuss your project<ArrowRight className="size-4"/></ButtonLink></div></section><section className="section-pad bg-[var(--paper)]"><div className="container-main grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><h2 className="font-display text-4xl font-semibold">What we deliver</h2><p className="mt-4 text-sm leading-7 text-[var(--muted)]">Scope is tailored after an initial diagnosis. Every project includes clear context, ownership, milestones and a way to evaluate progress.</p></div><div className="grid gap-3 sm:grid-cols-2">{deliverables.map(item=><div key={item} className="flex gap-3 rounded-2xl border border-[var(--line)] bg-white p-5 text-sm font-semibold"><Check className="size-4 shrink-0 text-[var(--brand-dark)]"/>{item}</div>)}</div></div></section><section className="bg-[var(--orange)] py-20"><div className="container-main flex items-end justify-between gap-8"><h2 className="max-w-4xl font-display text-4xl font-semibold tracking-[-.04em] md:text-6xl">Build the right commerce growth system for your stage</h2><ButtonLink href="/contact" variant="dark" size="lg">Contact AI Global</ButtonLink></div></section></>}
